name: 💫 Update Event
description: Update an existing event.
title: '<Event Name>'
labels: ["update event"]

body:
  - type: markdown
    attributes:
      value: |
        Before getting started, make sure you have found the event you want by providing the Year, Region and Event ID.
        If you cannot find the corresponding one, email directly to dev+swing@kjuly.com.

  - type: input
    id: region
    attributes:
      label: Region
      description: |
        The i18n locale identifier used to group your event.
        Please choose the appropriate one according to your country or region.
        * [Currently Collected Regions](https://swing.news/submit)
        * If you cannot find the corresponding one, use "Add Region" or email directly to dev+swing@kjuly.com.
      placeholder: e.g., zh_CN
    validations:
      required: true

  - type: input
    id: id
    attributes:
      label: Event ID
      description: |
        You can find the full list of existing event id at `https://github.com/swingdance/events/tree/main/<year>/<region_code>`.
        e.g., [https://github.com/swingdance/events/tree/main/2024/zh_CN](https://github.com/swingdance/events/tree/main/2024/zh_CN)

        Or visit https://swing.news and use the edit button on the event details page.
      placeholder: e.g., swingtime-ball-2024
    validations:
      required: true

  # Details to Update

  - type: markdown
    attributes:
      value: |
        ## Details to Update

        - Simply type in the fields you wish to update;
        - If you want to clear a field, enter an "x" to mark it for deletion.

  - type: input
    id: org_id
    attributes:
      label: Org ID
      description: ID of the host organization/community.
      placeholder: e.g., x-studio

  - type: input
    id: abb
    attributes:
      label: Name Abbreviate
      placeholder: e.g., STB

  - type: input
    id: name
    attributes:
      label: Name
      placeholder: e.g., Swingtime Ball

  - type: input
    id: name_local
    attributes:
      label: Local Name
      placeholder: e.g., Swingtime Ball

  - type: input
    id: session
    attributes:
      label: Session
      placeholder: e.g., 3

  - type: input
    id: date_starts
    attributes:
      label: Date Starts
      description: e.g., 2024-01-01
      placeholder: YYYY-MM-DD

  - type: input
    id: date_ends
    attributes:
      label: Date Ends
      description: e.g., 2024-01-03
      placeholder: YYYY-MM-DD

  - type: input
    id: city
    attributes:
      label: City
      placeholder: e.g., Xiamen

  - type: input
    id: province
    attributes:
      label: Province or State
      placeholder: e.g., Fujian
  
  - type: dropdown
    id: styles
    attributes:
      label: Specific dance style
      multiple: false
      default: 0
      options:
        - SAME
        - ANY
        - Balboa
        - Blues
        - Boogie Woogie
        - Shag

  - type: textarea
    id: venue
    attributes:
      label: Venue
      description: |
        The address of the studio or ballroom.
        * Leave blank to keep the original content.
      placeholder: |
        e.g. 
        B203, Zhuzong Building, No.25, East Third Ring Road, Beijing.
        北京市东三环中路25号住总大厦 B203。

  - type: textarea
    id: details
    attributes:
      label: Details
      description: |
        * Leave blank to keep the original content.
      placeholder: You can add event details here, or any other instructions or tips for dancers.

  - type: input
    id: email
    attributes:
      label: Email
      placeholder: e.g., abc@eample.com

  - type: input
    id: website
    attributes:
      label: Website or Homepage
      placeholder: e.g., https://example.com

  - type: markdown
    attributes:
      value: |
        Here are some optional fields for social network accounts that may be
        helpful in letting others know more about your eventanization/community.
        
        Please add the **User ID Only**, not the full URL link.
        For example, if the full URL is https://www.instagram.com/abc, add abc.
  
  - type: input
    id: fb
    attributes:
      label: Facebook
      placeholder: e.g., abc

  - type: input
    id: ig
    attributes:
      label: Instagram
      placeholder: e.g., abc

  - type: input
    id: yt
    attributes:
      label: YouTube
      placeholder: e.g., abc

  - type: input
    id: wo
    attributes:
      label: WeChat Official Account
      placeholder: e.g., abc

  - type: input
    id: bl
    attributes:
      label: Bilibili
      placeholder: e.g., abc

  - type: input
    id: rb
    attributes:
      label: Xiaohongshu
      placeholder: e.g., abc
